version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8280:8080"
    volumes:
      - ./realm-dify.json:/opt/keycloak/data/import/realm-dify.json
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/master"]
      interval: 5s
      timeout: 5s
      retries: 30


