# GitHub Action Configuration for Dify Enterprise SSO
# This file contains configuration parameters for the sync-dify workflow

name: Configuration

# Upstream repository configuration
upstream:
  repo: "langgenius/dify"
  branch: "main"
  sync_interval: "0 2 * * *"  # Daily at 2 AM UTC

# Docker configuration
docker:
  registry: "ghcr.io"
  image_prefix: "dify"
  platforms: ["linux/amd64", "linux/arm64"]  # Multi-platform support
  
# Build configuration
build:
  cache: true
  cache_type: "gha"  # GitHub Actions cache
  push_latest: true
  push_sha: true
  
# Patch configuration
patch:
  name: "dify-keycloak.diff"
  description: "Keycloak OAuth integration patch for Dify"
  files_to_preserve:
    - "dify-keycloak.diff"
    - "docker-compose.yaml"
    - "keycloak/"
    - ".github/workflows/"
    - "README.md"
    
# Environment variables to add/update
environment_variables:
  keycloak:
    - "KEYCLOAK_CLIENT_ID"
    - "KEYCLOAK_CLIENT_SECRET"
    - "KEYCLOAK_ISSUER_URL"
  oauth:
    - "ENABLE_SOCIAL_OAUTH_LOGIN"
  urls:
    - "CONSOLE_API_URL"
    - "CONSOLE_WEB_URL"
    - "SERVICE_API_URL"
    - "APP_API_URL"
    - "APP_WEB_URL"
    
# Release configuration
release:
  create: true
  draft: false
  prerelease: false
  tag_format: "v{date}-{time}"
  name_format: "Dify Enterprise SSO - {date} {time}"
  
# Notification configuration
notifications:
  pr_comment: true
  issue_comment: false
  summary: true
  
# Security configuration
security:
  require_reviews: false
  auto_merge: false
  branch_protection: false
